#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : autossh
Version  : 1.4g
Release  : 2
URL      : https://www.harding.motd.ca/autossh/autossh-1.4g.tgz
Source0  : https://www.harding.motd.ca/autossh/autossh-1.4g.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Distributable
Requires: autossh-bin = %{version}-%{release}
Requires: autossh-data = %{version}-%{release}
Requires: autossh-man = %{version}-%{release}
Requires: openssh
BuildRequires : openssh
BuildRequires : util-linux

%description
autossh is a program to start a copy of ssh and monitor it, restarting
it as necessary should it die or stop passing traffic.

%package bin
Summary: bin components for the autossh package.
Group: Binaries
Requires: autossh-data = %{version}-%{release}

%description bin
bin components for the autossh package.


%package data
Summary: data components for the autossh package.
Group: Data

%description data
data components for the autossh package.


%package doc
Summary: doc components for the autossh package.
Group: Documentation
Requires: autossh-man = %{version}-%{release}

%description doc
doc components for the autossh package.


%package man
Summary: man components for the autossh package.
Group: Default

%description man
man components for the autossh package.


%prep
%setup -q -n autossh-1.4g
cd %{_builddir}/autossh-1.4g

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604886331
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1604886331
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/autossh

%files data
%defattr(-,root,root,-)
/usr/share/examples/autossh/autossh.host
/usr/share/examples/autossh/rscreen

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/autossh/*

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/autossh.1
